dotnet-version: 8.0
benchmark-expire-min: 10
benchmark-client-run-script-path: ".github/scripts/benchmark-client-run.sh"
benchmark-client-run-script-args: "--args \"-u http://${BENCHMARK_SERVER_NAME}:5000 --protocol {{ protocol }} -s CI --rounds 8 --channels {{ channels }} --streams {{ streams }} --serialization {{ serialization }} --validate true --tags {{ tags }}\""
benchmark-server-run-script-path: ".github/scripts/benchmark-server-run.sh"
benchmark-server-run-script-args: "--args \"-u http://0.0.0.0:5000 --protocol {{ protocol }} --validate true --tags {{ tags }}\""
benchmark-server-stop-script-path: ".github/scripts/benchmark-server-stop.sh"
jobs:
  # 1
  - match: messagepack-h2c-linux-1
    tags: legend:messagepack-h2c-linux,streams:1,protocol:h2c
    protocol: h2c
    channels: 28
    streams: 1
    serialization: messagepack
  # 1x1
  - match: messagepack-h2c-linux-1x1
    tags: "legend:messagepack-h2c-linux,streams:1x1,protocol:h2c"
    protocol: h2c
    channels: 1
    streams: 1
    serialization: messagepack
