name: Check all .meta is commited
description: Check all Unity .meta files are committed.
inputs:
  directory:
    description: Working directory to check change
    required: true
  exit-on-error:
    description: Exit on error
    required: false
    default: "true"
outputs:
  meta-exists:
    description: If .meta file exists
    value: ${{ steps.check-meta.outputs.meta-exists }}

runs:
  using: "composite"
  steps:
    - name: Check .meta exists
      id: check-meta
      shell: bash
      run: |
        if git ls-files --others --exclude-standard -t | grep --regexp='[.]meta$'; then
          echo "Detected .meta file generated. Do you forgot commit a .meta file?"
          echo "meta-exists=true" | tee -a "$GITHUB_OUTPUT"
          if [[ "${{inputs.exit-on-error }}" == "true" ]]; then
            exit 1
          fi
        else
          echo "Great, all .meta files are commited."
          echo "meta-exists=false" | tee -a "$GITHUB_OUTPUT"
        fi
      working-directory: ${{ inputs.directory }}
