name: (R) Prevent github workflow change
on:
  workflow_call:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/**/*.yaml"
      - ".github/**/*.yml"

# prevent fork user to change
jobs:
  detect:
    if: ${{ ! startsWith(github.event.pull_request.head.label, format('{0}:', github.repository_owner)) }} # only apply to pull_request
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: "Prevent file change"
        run: exit 1
