name: Test benchmark_config2matrix

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmark_config2matrix
        id: actual
        run: bash ./.github/scripts/benchmark_config2matrix.sh --benchmark-config-path ./.github/scripts/tests/template_benchmark_config.yaml
      - name: Test
        run: |
          expected=$(jq -c < ./.github/scripts/tests/template_benchmark_config.json)
          actual=$(echo '${{ steps.actual.outputs.matrix }}' | jq -c)

          echo -n "FACT: matrix is sane as expected json"
          if [[ "$actual" == "$expected" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
