name: Test validate-tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: GitHub Tag to release. ex) 1.1.0"
        required: true
        default: ""
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  validate:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/validate-tag.yaml
    with:
      tag: "1.10.0"
      no-fail-on-error: false
    secrets: inherit

  validate2:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/validate-tag.yaml
    with:
      tag: "1.0.0"
      no-fail-on-error: true
    secrets: inherit

  test:
    needs: [validate, validate2]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Test
        run: |
          echo "DEBUG: validate: ${{ needs.validate.outputs.result }}"
          echo "DEBUG: validate2: ${{ needs.validate2.outputs.result }}"

          echo -n "FACT: tag is newer then current release"
          if [[ "${{ needs.validate.outputs.result }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi

          echo -n "FACT: tag is old then current release"
          if [[ "${{ needs.validate2.outputs.result }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
