name: Test update-packagejson

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: GitHub Tag to release. ex) 1.1.0"
        required: true
        default: ""
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  update-packagejson:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/update-packagejson.yaml
    with:
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
      file-path: |
        ./Sandbox/Sandbox.Unity/Assets/Plugins/Foo/package.json
        ./Sandbox/Sandbox.Godot/addons/Foo/plugin.cfg
      tag: "${{ github.event_name == 'workflow_dispatch' && inputs.tag || format('1.0.{0}', github.run_id) }}"
      dry-run: true

  cleanup:
    if: ${{ needs.update-packagejson.outputs.is-branch-created == 'true' }}
    needs: [update-packagejson]
    uses: ./.github/workflows/clean-packagejson-branch.yaml
    with:
      branch: ${{ needs.update-packagejson.outputs.branch-name }}
