name: Test GitHub Actions

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-dotnet
      - name: dotnet build
        run: dotnet build
        working-directory: ./Sandbox

  update-packagejson:
    uses: ./.github/workflows/update-packagejson.yaml
    with:
      file-path: ./Sandbox/Sandbox.Unity/Assets/Plugins/Foo/package.json
      tag: 2.0.0
      dry-run: true

  cleanup:
    if: needs.update-packagejson.outputs.is-branch-created == 'true'
    needs: [update-packagejson]
    uses: ./.github/workflows/clean-packagejson-branch.yaml
    with:
      branch: ${{ needs.update-packagejson.outputs.branch-name }}
