name: Test GitHub Actions

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: ./Sandbox
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-dotnet
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build -c Release
      - name: dotnet pack
        run: dotnet pack -c Release --no-build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: ./Sandbox/ClassLibrary/bin/Release/*.nupkg

  create-release:
    needs: [update-packagejson]
    uses: ./.github/workflows/create-release.yaml
    with:
      commit-id: ${{ needs.update-packagejson.outputs.sha }}
      tag: "0.1.0"
      dry-run: true
      nuget-push: true # dry-run なので pushはされない。

  update-packagejson:
    uses: ./.github/workflows/update-packagejson.yaml
    with:
      file-path: |
        ./Sandbox/Sandbox.Unity/Assets/Plugins/Foo/package.json
        ./Sandbox/Sandbox.Godot/addons/Foo/plugin.cfg
      tag: 2.0.0
      dry-run: true

  cleanup:
    if: ${{ needs.update-packagejson.outputs.is-branch-created == 'true' }}
    needs: [update-packagejson]
    uses: ./.github/workflows/clean-packagejson-branch.yaml
    with:
      branch: ${{ needs.update-packagejson.outputs.branch-name }}
