name: Test clean-packagejson-branch

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create branch
        run: |
          git checkout -b test-branch
          git push origin test-branch

  cleanup:
    needs: [create-branch]
    uses: ./.github/workflows/clean-packagejson-branch.yaml
    with:
      branch: test-branch
