name: Test validate-tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: GitHub Tag to release. ex) 1.1.0"
        required: true
        default: ""
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/validate-tag
        id: validate
        with:
          tag: ${{ inputs.tag || '1.10.0' }}
          no-fail-on-error: false
      - uses: ./.github/actions/validate-tag
        id: validate2
        with:
          tag: ${{ inputs.tag || '1.0.0' }}
          no-fail-on-error: true
      - name: Test
        run: |
          echo "DEBUG: validate: ${{ steps.validate.outputs.result }}"
          echo "DEBUG: validate2: ${{ steps.validate2.outputs.result }}"

          echo -n "FACT: tag is newer then current release"
          if [[ "${{ steps.validate.outputs.result }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi

          echo -n "FACT: tag is old then current release"
          if [[ "${{ steps.validate2.outputs.result }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
