name: TOC Generator

on:
  push:
    branches: ["main"]
    paths:
      - "README.md"

jobs:
  toc:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "# 📖 Table of Contents"
          FOLDING: false
