name: (R) Update package.json

on:
  workflow_call:
    inputs:
      file-path:
        description: "file-path: package.json path to update."
        required: true
        type: string
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
        type: string
      dry-run:
        description: "dry_run: true will never create release/nuget."
        required: true
        default: false
        type: boolean

jobs:
  update-packagejson:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
    steps:
      - name: Configure Environment Variables
        run: |
          echo "FILE_PaATH=${inputs.packagejson}" | tee -a "$GITHUB_ENV"
          echo "GIT_TAG=${inputs.tag}" | tee -a "$GITHUB_ENV"
          echo "DRY_RUN=${inputs.dry-run}" | tee -a "$GITHUB_ENV"

      - uses: actions/checkout@v3

      - name: Output package.json (Before)
        run: cat ${{ env.FILE_PATH}}

      - name: Update package.json to version ${{ env.GIT_TAG }}
        run: sed -i -e "s/\(\"version\":\) \"\(.*\)\",/\1 \"${{ env.GIT_TAG }}\",/" ${{ env.FILE_PATH }}

      - name: Check update
        id: check_update
        run: |
          cat ${{ env.FILE_PATH}}
          git diff --exit-code || echo "::set-output name=changed::1"

      - name: Commit files
        id: commit
        if: steps.check_update.outputs.changed == '1'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "feat: Update package.json to ${{ env.GIT_TAG }}" -a
          echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Check sha
        run: echo "SHA ${SHA}"
        env:
          SHA: ${{ steps.commit.outputs.sha }}

      - name: Create Tag
        if: steps.check_update.outputs.changed == '1'
        run: git tag ${{ env.GIT_TAG }}

      - name: Push changes
        if: env.DRY_RUN == 'false' && steps.check_update.outputs.changed == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Push changes (dry_run)
        if: env.DRY_RUN == 'true' && steps.check_update.outputs.changed == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.DRY_RUN_BRANCH_PREFIX }}-${{ env.GIT_TAG }}
          tags: false
